title:              "ZERVWAVE INDUSTRIES"
keywords:           "zerv,zervwave,zervwave industries,robot,animator,illustration,indie game,game,pixel art,pixel game"
description:        "Indie Game, Animation and Robot."
url:                "https://zervwave.com"
locale:              "en"
author:
  name:             "Harvey Wu (@zervwave)"
  email:            "harveywu@outlook.it"

# Link format
permalink:          pretty

# Markdown
markdown:           kramdown

# Assets
sass:
  sass_dir:         _sass
  style:            compressed

plugins:
  - jekyll-seo-tag