title:              "Zervwave Industries"
keywords:           "zerv,zervwave,zervwave industries,robot,animator,illustration,indie game,game,pixel art,pixel game"
description:        "Animation, Indie Game and Robot."
url:                "https://zervwave.com"
name:               "Harvey Wu (@zervwave)"
email:              "harveywu@outlook.it"

# Navbar title
navbar:
  title:
    first:          "ZERVWAVE"
    second:         "I"
    third:          "NDUSTRIES"

# Latest blog show in the home page.
maxPost:            8

# POST Category Options:
#    [T]ECHNOLOGY
#    [D]EVELOPMENT
#    [U]PDATE
#    [O]THER
# More information in _includes/posts.html

# Link format
permalink:          pretty

# Social link information in _data/social.yml

# Markdown
markdown:           kramdown

# Assets
sass:
  sass_dir:         _sass
  style:            compressed

# *.webp, *.jpg, *png.
plakat:
  url:              https://pic1.zhimg.com/v2-d91895053f7826a10a9264878399572c_b.webp
  location:         center
  slogan:           Hi there !

menu:
  - name: "HOME"
    url: /
  - name: "BLOGS"
    url: /blogs
  - name: "WORKS"
    url: /works
  - name: "ABOUT"
    url: /about

plugins:
  - jekyll-seo-tag