title:              "ZERVWAVE DYNAMICS INDUSTRIES"
keywords:           "zerv,zervwave,zervwave industries,robot,animator,illustration,indie game,game,pixel art,pixel game"
description:        "Animation, Robot and Indie Game."
name:               "Harvey Wu (zervwave)"
url:                "https://zervwave.com"

author:
  name:             "Harvey Wu (zervwave)"
  email:            "harveywu@outlook.it"

permalink:          pretty

# Social Link
steam_username:     zervwave
github_username:    zervwave
twitter_username:   zervwave
bilibili_username:  zervwave

markdown:           kramdown

plugins:
  - jekyll-seo-tag
  
# Assets
sass:
  sass_dir:         _sass
  style:            compressed

