title:              "Zervwave Dynamics Industries"
keywords:           "zerv,zervwave,zervwave industries,robot,animator,illustration,indie game,game,pixel art,pixel game"
description:        "Animation, Indie Game and Robot."
name:               "Harvey Wu (zervwave)"
url:                "https://zervwave.com"

# Author Information
author:
  name:             "Harvey Wu (zervwave)"
  email:            "harveywu@outlook.it"

permalink:          pretty

# Social Link
steam:              zervwave
github:             zervwave
twitter:            zervwave
bilibili:           zervwave

markdown:           kramdown

plugins:
  - jekyll-seo-tag
  
# Assets
sass:
  sass_dir:         _sass
  style:            compressed
