title:              "Zervwave Industries"
keywords:           "zerv,zervwave,zervwave industries,robot,animator,illustration,indie game,game,pixel art,pixel game"
description:        "Animation, Indie Game and Robot."
url:                "https://zervwave.com"
name:               "Harvey Wu (@zervwave)"
email:              "harveywu@outlook.it"
local:              "en"

# Navbar title
navbar:
  title:
    first:          "ZERVWAVE"
    second:         "I"
    third:          "NDUSTRIES"

# The latest posts show up to 8 and they are in a grid layout, 
# so it is a bit difficult to change to other numbers.
#
# POST Category Options:
#    [T]ECHNOLOGY
#    [D]EVELOPMENT
#    [U]PDATE
#    [O]THER
#
# More information in 
# _includes/posts.html
# _sass/orata/posts.scss

# Link format
permalink:          pretty

# Social link information in _data/social.yml

# Markdown
markdown:           kramdown

# Assets
sass:
  sass_dir:         _sass
  style:            compressed

# *.webp, *.jpg, *png.
plakat:
  url:              https://pic1.zhimg.com/v2-d91895053f7826a10a9264878399572c_b.webp
  location:         center
  slogan:           Hi there !
  author:           Internet

works:
  - name: "bna"
    url: http://www.st-trigger.co.jp/wp-content/uploads/2020/07/BNA_icon_02-250x250.jpg
  - name: "bna"
    url: http://www.st-trigger.co.jp/wp-content/uploads/2018/10/Icon_B-250x250.png
  - name: "bna"
    url: http://www.st-trigger.co.jp/wp-content/uploads/2016/12/LWATV_Key-250x250.png
  - name: "bna"
    url: http://www.st-trigger.co.jp/wp-content/uploads/2016/01/lwa2_250.png
  - name: "bna"
    url: http://www.st-trigger.co.jp/wp-content/uploads/2015/11/box_01.png
  - name: "bna"
    url: http://www.st-trigger.co.jp/wp-content/uploads/2020/07/BNA_icon_02-250x250.jpg
  - name: "bna"
    url: http://www.st-trigger.co.jp/wp-content/uploads/2018/10/Icon_B-250x250.png
  - name: "bna"
    url: http://www.st-trigger.co.jp/wp-content/uploads/2016/12/LWATV_Key-250x250.png
  - name: "bna"
    url: http://www.st-trigger.co.jp/wp-content/uploads/2016/01/lwa2_250.png
  - name: "bna"
    url: http://www.st-trigger.co.jp/wp-content/uploads/2015/11/box_01.png

anibar:
  url: https://pic3.zhimg.com/v2-06c679362f9e3c3e9f84ae5dbf5752c1_b.webp

menu:
  - name: "HOME"
    url: /
  - name: "BLOGS"
    url: /blogs
  - name: "WORKS"
    url: /works
  - name: "ABOUT"
    url: /about

plugins:
  - jekyll-seo-tag