title:              "Zervwave Dynamics Industries"
keywords:           "zerv,zervwave,zervwave industries,robot,animator,illustration,indie game,game,pixel art,pixel game"
description:        "Animation, Indie Game and Robot."
url:                "https://zervwave.com"
name:               "Harvey Wu (@zervwave)"
email:              "harveywu@outlook.it"

maxPost:            7

permalink:          pretty

# Social link information in _data/social.yml

# Markdown
markdown:           kramdown

# Assets
sass:
  sass_dir:         _sass
  style:            compressed

plakat:
  url:              https://images2.alphacoders.com/884/thumb-1920-884331.jpg
  location:         center
  slogan:           Hi there !

menu:
  - name: "HOME"
    url: /
  - name: "BLOGS"
    url: /blogs
  - name: "WORKS"
    url: /works
  - name: "ABOUT"
    url: /about

classify:
  - id: "1"
    name: "Animation"
    url: /animation
    bg: "classify-image.png"
    
  - id: "2"
    name: "Indie Game"
    url: /indie-game
    bg: "classify-image.png"
    
  - id: "3"
    name: "Robot"
    url: /robot
    bg: "classify-image.png"
    
  - id: "4"
    name: "Other"
    url: /other
    bg: "classify-image.png"

plugins:
  - jekyll-seo-tag
